import type { ModelMetadata } from "./model-catalog-types";

export const curatedModels: ModelMetadata[] = [
  {
    id: "openai:chatgpt-4o-latest",
    providerId: "openai",
    providerName: "OpenAI",
    modelId: "chatgpt-4o-latest",
    name: "ChatGPT-4o Latest",
    description: "Latest GPT-4o experience with adaptive responses",
    release: "2025-08",
    contextWindow: 128_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal", "memory"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "openai:gpt-4.1",
    providerId: "openai",
    providerName: "OpenAI",
    modelId: "gpt-4.1",
    name: "GPT-4.1",
    description: "Flagship OpenAI reasoning model with tool and vision support",
    release: "2024-12",
    contextWindow: 128_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "reasoning", "tooling"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "openai:gpt-4o",
    providerId: "openai",
    providerName: "OpenAI",
    modelId: "gpt-4o",
    name: "GPT-4o",
    description:
      "Multimodal OpenAI model with high-quality chat and vision support",
    release: "2024-05",
    contextWindow: 128_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "vision"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "google:gemini-2.0-flash",
    providerId: "google",
    providerName: "Google Gemini",
    modelId: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    description: "High-speed multimodal Gemini model with streaming",
    release: "2025-02",
    contextWindow: 1_000_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "google:gemini-2.5-flash",
    providerId: "google",
    providerName: "Google Gemini",
    modelId: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    description: "Latest fast Gemini model with strong multimodal performance",
    release: "2025-05",
    contextWindow: 1_000_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "google:gemini-2.5-flash-lite",
    providerId: "google",
    providerName: "Google Gemini",
    modelId: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    description:
      "Lightweight Gemini Flash model optimized for fast, low-cost generation",
    release: "2025-09",
    contextWindow: 1_000_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "multimodal"],
    tags: ["curated", "fast"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "google:gemini-1.5-pro",
    providerId: "google",
    providerName: "Google Gemini",
    modelId: "gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    description: "Extended context Gemini model for complex reasoning",
    release: "2024-06",
    contextWindow: 1_000_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "reasoning"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "openrouter:anthropic/claude-3.5-sonnet",
    providerId: "openrouter",
    providerName: "OpenRouter",
    modelId: "anthropic/claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    description: "Premium Claude reasoning model via OpenRouter",
    release: "2024-07",
    modalities: ["text", "vision"],
    capabilities: ["chat", "reasoning"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "openrouter:deepseek/deepseek-r1",
    providerId: "openrouter",
    providerName: "OpenRouter",
    modelId: "deepseek/deepseek-r1",
    name: "DeepSeek R1",
    description: "Open-source DeepSeek reasoning model",
    release: "2025-01",
    modalities: ["text"],
    capabilities: ["chat", "reasoning", "code"],
    tags: ["open-source", "curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "cloudflare-workers:@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    providerId: "cloudflare-workers",
    providerName: "Cloudflare Workers AI",
    modelId: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    name: "Llama 3.3 70B Instruct (FP8)",
    description: "Low-latency Llama via Cloudflare Workers AI",
    release: "2025-09",
    modalities: ["text"],
    capabilities: ["chat", "code"],
    tags: ["curated", "fast"],
    source: "curated",
    isCurated: true,
  },

  {
    id: "vercel-gateway:xai/grok-2-vision-1212",
    providerId: "vercel-gateway",
    providerName: "Vercel AI Gateway",
    modelId: "xai/grok-2-vision-1212",
    name: "Grok 2 Vision",
    description: "Multimodal Grok model accessible via Vercel AI Gateway",
    release: "2024-12",
    modalities: ["text", "vision"],
    capabilities: ["chat", "multimodal"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "vercel-gateway:xai/grok-3-mini",
    providerId: "vercel-gateway",
    providerName: "Vercel AI Gateway",
    modelId: "xai/grok-3-mini",
    name: "Grok 3 Mini",
    description: "Reasoning-focused Grok model via Vercel AI Gateway",
    release: "2025-02",
    modalities: ["text"],
    capabilities: ["reasoning"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "vercel-gateway:openai/gpt-4.1",
    providerId: "vercel-gateway",
    providerName: "Vercel AI Gateway",
    modelId: "openai/gpt-4.1",
    name: "GPT-4.1 (Vercel Gateway)",
    description:
      "Flagship OpenAI reasoning model routed through Vercel AI Gateway",
    release: "2024-12",
    contextWindow: 128_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "reasoning", "tooling"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "vercel-gateway:openai/gpt-4o",
    providerId: "vercel-gateway",
    providerName: "Vercel AI Gateway",
    modelId: "openai/gpt-4o",
    name: "GPT-4o (Vercel Gateway)",
    description:
      "OpenAI GPT-4o served via Vercel AI Gateway with multimodal support",
    release: "2024-05",
    contextWindow: 128_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "vision"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "vercel-gateway:openai/gpt-4o-mini",
    providerId: "vercel-gateway",
    providerName: "Vercel AI Gateway",
    modelId: "openai/gpt-4o-mini",
    name: "GPT-4o mini (Vercel Gateway)",
    description: "Fast OpenAI GPT-4o mini via Vercel AI Gateway",
    release: "2024-07",
    contextWindow: 128_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "vision"],
    tags: ["curated", "fast"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "vercel-gateway:google/gemini-2.5-flash",
    providerId: "vercel-gateway",
    providerName: "Vercel AI Gateway",
    modelId: "google/gemini-2.5-flash",
    name: "Gemini 2.5 Flash (Vercel Gateway)",
    description: "Latest Google Gemini flash model via Vercel AI Gateway",
    release: "2025-05",
    contextWindow: 1_000_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "cloudflare-gateway:openai/gpt-4o",
    providerId: "cloudflare-gateway",
    providerName: "Cloudflare AI Gateway",
    modelId: "openai/gpt-4o",
    name: "GPT-4o (Cloudflare Gateway)",
    description:
      "OpenAI GPT-4o routed via Cloudflare AI Gateway with multimodal support",
    release: "2024-05",
    contextWindow: 128_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "vision"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "cloudflare-gateway:openai/gpt-4o-mini",
    providerId: "cloudflare-gateway",
    providerName: "Cloudflare AI Gateway",
    modelId: "openai/gpt-4o-mini",
    name: "GPT-4o mini (Cloudflare Gateway)",
    description: "Low-latency GPT-4o mini through Cloudflare AI Gateway",
    release: "2024-07",
    contextWindow: 128_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "vision"],
    tags: ["curated", "fast"],
    source: "curated",
    isCurated: true,
  },
  {
    id: "cloudflare-gateway:google/gemini-2.5-flash",
    providerId: "cloudflare-gateway",
    providerName: "Cloudflare AI Gateway",
    modelId: "google/gemini-2.5-flash",
    name: "Gemini 2.5 Flash (Cloudflare Gateway)",
    description:
      "Latest Gemini flash model available through Cloudflare AI Gateway",
    release: "2025-05",
    contextWindow: 1_000_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
  },
];
