import type { ModelMetadata } from "./model-catalog-types";

/**
 * Curated list of latest reasoning and chat models from major providers (October 2025)
 * Only includes models currently available in production APIs
 * Deprecated and older versions have been removed
 */
export const curatedModels: ModelMetadata[] = [
  // ============================================================================
  // OPENAI - Latest Models
  // ============================================================================
  {
    id: "openai:gpt-4o-latest",
    providerId: "openai",
    providerName: "OpenAI",
    modelId: "gpt-4o-latest",
    name: "GPT-4o Latest",
    description:
      "Latest GPT-4o with adaptive responses and multimodal capabilities",
    release: "2025-08",
    contextWindow: 128_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal", "memory"],
    tags: ["curated", "latest"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },
  {
    id: "openai:o3-mini",
    providerId: "openai",
    providerName: "OpenAI",
    modelId: "o3-mini",
    name: "GPT-o3-mini",
    description: "Latest OpenAI reasoning model with high effort reasoning",
    release: "2025-01",
    contextWindow: 128_000,
    modalities: ["text"],
    capabilities: ["chat", "reasoning", "code"],
    tags: ["curated", "reasoning", "latest"],
    source: "curated",
    isCurated: true,
    reasoningType: "openai-thinking",
    thinkingBudget: 8000,
  },
  {
    id: "openai:gpt-4.1",
    providerId: "openai",
    providerName: "OpenAI",
    modelId: "gpt-4.1",
    name: "GPT-4.1",
    description: "OpenAI reasoning model with tool and vision support",
    release: "2024-12",
    contextWindow: 128_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "reasoning", "tooling"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
    reasoningType: "openai-thinking",
    thinkingBudget: 6000,
  },

  // ============================================================================
  // GOOGLE GEMINI - Latest Models
  // ============================================================================
  {
    id: "google:gemini-2.0-flash-exp",
    providerId: "google",
    providerName: "Google Gemini",
    modelId: "gemini-2.0-flash-exp",
    name: "Gemini 2.0 Flash Experimental",
    description:
      "Latest Google Gemini 2.0 Flash with experimental features and high speed",
    release: "2025-09",
    contextWindow: 1_000_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal", "code"],
    tags: ["curated", "latest", "experimental"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },
  {
    id: "google:gemini-2.5-pro",
    providerId: "google",
    providerName: "Google Gemini",
    modelId: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    description:
      "Advanced Gemini model with strong reasoning and coding - supports thinking summaries",
    release: "2025-05",
    contextWindow: 1_000_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "reasoning", "vision", "code"],
    tags: ["curated", "reasoning"],
    source: "curated",
    isCurated: true,
    reasoningType: "gemini-thinking",
    thinkingBudget: -1,
  },

  // ============================================================================
  // GOOGLE GEMINI 2.5 - Full Model Family
  // ============================================================================
  {
    id: "google:gemini-2.5-flash",
    providerId: "google",
    providerName: "Google Gemini",
    modelId: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    description: "Fast Gemini model optimized for speed and efficiency",
    release: "2025-05",
    contextWindow: 1_000_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal", "reasoning"],
    tags: ["curated", "fast", "reasoning"],
    source: "curated",
    isCurated: true,
    reasoningType: "gemini-thinking",
    thinkingBudget: -1,
  },
  {
    id: "google:gemini-2.5-flash-lite",
    providerId: "google",
    providerName: "Google Gemini",
    modelId: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    description:
      "Ultra-fast and cost-efficient model for high-volume latency-sensitive tasks",
    release: "2025-06",
    contextWindow: 1_000_000,
    modalities: ["text"],
    capabilities: ["chat", "code", "reasoning"],
    tags: ["curated", "fast", "lightweight", "reasoning"],
    source: "curated",
    isCurated: true,
    reasoningType: "gemini-thinking",
    thinkingBudget: -1,
  },
  {
    id: "google:gemini-2.5-flash-image",
    providerId: "google",
    providerName: "Google Gemini",
    modelId: "gemini-2.5-flash-image",
    name: "Gemini 2.5 Flash Image (Nano Banana)",
    description:
      "Advanced image generation and editing model with character consistency and multimodal blending",
    release: "2025-06",
    contextWindow: 4096,
    modalities: ["text", "vision"],
    capabilities: ["image-generation", "multimodal"],
    tags: ["curated", "image-gen", "latest"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },

  // ============================================================================
  // GOOGLE IMAGE GENERATION MODELS
  // ============================================================================
  {
    id: "google:imagen-4-generation",
    providerId: "google",
    providerName: "Google Vertex AI",
    modelId: "imagen-4-generation",
    name: "Imagen 4 Generation",
    description:
      "High-quality text-to-image generation with superior prompt adherence",
    release: "2025-06",
    contextWindow: 4096,
    modalities: ["text"],
    capabilities: ["image-generation"],
    tags: ["curated", "image-gen"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },
  {
    id: "google:imagen-4-fast",
    providerId: "google",
    providerName: "Google Vertex AI",
    modelId: "imagen-4-fast",
    name: "Imagen 4 Fast",
    description: "Optimized for low-latency image generation",
    release: "2025-06",
    contextWindow: 4096,
    modalities: ["text"],
    capabilities: ["image-generation"],
    tags: ["curated", "image-gen", "fast"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },
  {
    id: "google:imagen-4-ultra",
    providerId: "google",
    providerName: "Google Vertex AI",
    modelId: "imagen-4-ultra",
    name: "Imagen 4 Ultra",
    description: "Premium image generation with maximum quality",
    release: "2025-06",
    contextWindow: 4096,
    modalities: ["text"],
    capabilities: ["image-generation"],
    tags: ["curated", "image-gen", "premium"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },

  // ============================================================================
  // GOOGLE VIDEO GENERATION MODELS (VEO)
  // ============================================================================
  {
    id: "google:veo-3-generation",
    providerId: "google",
    providerName: "Google Vertex AI",
    modelId: "veo-3-generation",
    name: "Veo 3 Generation",
    description: "High-quality video generation from text and images",
    release: "2025-06",
    contextWindow: 4096,
    modalities: ["text", "vision"],
    capabilities: ["video-generation"],
    tags: ["curated", "video-gen"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },
  {
    id: "google:veo-3-fast",
    providerId: "google",
    providerName: "Google Vertex AI",
    modelId: "veo-3-fast",
    name: "Veo 3 Fast",
    description: "Fast video generation balancing speed and quality",
    release: "2025-06",
    contextWindow: 4096,
    modalities: ["text", "vision"],
    capabilities: ["video-generation"],
    tags: ["curated", "video-gen", "fast"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },

  // ============================================================================
  // OPENAI IMAGE GENERATION MODELS
  // ============================================================================
  {
    id: "openai:dall-e-3",
    providerId: "openai",
    providerName: "OpenAI",
    modelId: "dall-e-3",
    name: "DALL-E 3",
    description: "Advanced text-to-image generation with superior quality",
    release: "2023-11",
    contextWindow: 4096,
    modalities: ["text"],
    capabilities: ["image-generation"],
    tags: ["curated", "image-gen"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },

  // ============================================================================
  // ANTHROPIC CLAUDE - Latest Models
  // ============================================================================
  {
    id: "openrouter:anthropic/claude-3.7-sonnet",
    providerId: "openrouter",
    providerName: "Anthropic (via OpenRouter)",
    modelId: "anthropic/claude-3.7-sonnet",
    name: "Claude 3.7 Sonnet",
    description: "Latest Claude with extended thinking mode for deep reasoning",
    release: "2025-02",
    contextWindow: 200_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "reasoning", "vision"],
    tags: ["curated", "latest"],
    source: "curated",
    isCurated: true,
    reasoningType: "anthropic-thinking",
    thinkingBudget: 8000,
  },
  {
    id: "openrouter:anthropic/claude-3.5-sonnet",
    providerId: "openrouter",
    providerName: "Anthropic (via OpenRouter)",
    modelId: "anthropic/claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    description:
      "High-performance Claude model with strong coding capabilities",
    release: "2024-06",
    contextWindow: 200_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "vision", "code"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },

  // ============================================================================
  // DEEPSEEK - Latest Models
  // ============================================================================
  {
    id: "openrouter:deepseek/deepseek-r1",
    providerId: "openrouter",
    providerName: "DeepSeek (via OpenRouter)",
    modelId: "deepseek/deepseek-r1",
    name: "DeepSeek R1",
    description: "Open-source reasoning model with native chain-of-thought",
    release: "2025-01",
    modalities: ["text"],
    capabilities: ["chat", "reasoning", "code"],
    tags: ["curated", "open-source", "reasoning"],
    source: "curated",
    isCurated: true,
    reasoningType: "deepseek-thinking",
    thinkingBudget: 6000,
  },

  // ============================================================================
  // XAI GROK - Latest Models
  // ============================================================================
  {
    id: "vercel-gateway:xai/grok-3",
    providerId: "vercel-gateway",
    providerName: "xAI (via Vercel Gateway)",
    modelId: "xai/grok-3",
    name: "Grok 3",
    description: "Latest xAI Grok with think mode for reasoning tasks",
    release: "2025-08",
    contextWindow: 128_000,
    modalities: ["text"],
    capabilities: ["chat", "reasoning", "code"],
    tags: ["curated", "latest"],
    source: "curated",
    isCurated: true,
    reasoningType: "internal-thinking",
    thinkingBudget: 6000,
  },

  // ============================================================================
  // ALIBABA QWEN - Latest Models
  // ============================================================================
  {
    id: "openrouter:qwen/qwen-max",
    providerId: "openrouter",
    providerName: "Alibaba Qwen (via OpenRouter)",
    modelId: "qwen/qwen-max",
    name: "Qwen Max",
    description: "Latest Alibaba Qwen model with strong reasoning capabilities",
    release: "2025-04",
    contextWindow: 200_000,
    modalities: ["text"],
    capabilities: ["chat", "reasoning", "code"],
    tags: ["curated"],
    source: "curated",
    isCurated: true,
    reasoningType: "internal-thinking",
  },

  // ============================================================================
  // META LLAMA - Latest Models (via Cloudflare)
  // ============================================================================
  {
    id: "cloudflare-workers:@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    providerId: "cloudflare-workers",
    providerName: "Meta Llama (via Cloudflare)",
    modelId: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    name: "Llama 3.3 70B Instruct",
    description: "Latest Meta Llama 3.3 model optimized for fast inference",
    release: "2025-09",
    modalities: ["text"],
    capabilities: ["chat", "code"],
    tags: ["curated", "open-source"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },

  // ============================================================================
  // VERCEL GATEWAY - Routed Latest Models
  // ============================================================================
  {
    id: "vercel-gateway:openai/gpt-4o-latest",
    providerId: "vercel-gateway",
    providerName: "Vercel AI Gateway",
    modelId: "openai/gpt-4o-latest",
    name: "GPT-4o Latest (Gateway)",
    description:
      "Latest OpenAI GPT-4o routed through Vercel AI Gateway for optimized performance",
    release: "2025-08",
    contextWindow: 128_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal", "memory"],
    tags: ["curated", "gateway"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },
  {
    id: "vercel-gateway:openai/gpt-4.1",
    providerId: "vercel-gateway",
    providerName: "Vercel AI Gateway",
    modelId: "openai/gpt-4.1",
    name: "GPT-4.1 (Gateway)",
    description: "OpenAI reasoning model via Vercel AI Gateway",
    release: "2024-12",
    contextWindow: 128_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "reasoning", "tooling"],
    tags: ["curated", "gateway"],
    source: "curated",
    isCurated: true,
    reasoningType: "openai-thinking",
    thinkingBudget: 6000,
  },
  {
    id: "vercel-gateway:google/gemini-2.5-flash",
    providerId: "vercel-gateway",
    providerName: "Vercel AI Gateway",
    modelId: "google/gemini-2.5-flash",
    name: "Gemini 2.5 Flash (Gateway)",
    description: "Fast Google Gemini model routed via Vercel AI Gateway",
    release: "2025-05",
    contextWindow: 1_000_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal"],
    tags: ["curated", "gateway", "fast"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },
  {
    id: "cloudflare-ai-gateway:@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    providerId: "cloudflare-ai-gateway",
    providerName: "Cloudflare AI Gateway",
    modelId: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    name: "Llama 3.3 70B Instruct (CF Gateway)",
    description:
      "Primary Cloudflare Workers AI model via AI Gateway with Gemini 2.5 Flash-Lite fallback",
    release: "2025-09",
    contextWindow: 128_000,
    modalities: ["text"],
    capabilities: ["chat", "code"],
    tags: ["curated", "gateway", "cloudflare"],
    source: "curated",
    isCurated: true,
    reasoningType: "none",
  },
  {
    id: "cloudflare-ai-gateway:gemini-2.5-flash",
    providerId: "cloudflare-ai-gateway",
    providerName: "Cloudflare AI Gateway",
    modelId: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash (CF Gateway)",
    description:
      "Google Gemini 2.5 Flash via Cloudflare AI Gateway with flash-lite fallback",
    release: "2025-05",
    contextWindow: 1_000_000,
    modalities: ["text", "vision", "audio"],
    capabilities: ["chat", "multimodal", "reasoning"],
    tags: ["curated", "gateway", "fast", "reasoning"],
    source: "curated",
    isCurated: true,
    reasoningType: "gemini-thinking",
    thinkingBudget: -1,
  },
  {
    id: "cloudflare-ai-gateway:gemini-2.5-pro",
    providerId: "cloudflare-ai-gateway",
    providerName: "Cloudflare AI Gateway",
    modelId: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro (CF Gateway)",
    description:
      "Advanced Google Gemini 2.5 Pro via Cloudflare AI Gateway with flash fallback",
    release: "2025-05",
    contextWindow: 1_000_000,
    modalities: ["text", "vision"],
    capabilities: ["chat", "reasoning", "vision", "code"],
    tags: ["curated", "gateway", "reasoning"],
    source: "curated",
    isCurated: true,
    reasoningType: "gemini-thinking",
    thinkingBudget: -1,
  },
];
