/**
 * Create Chat Action
 *
 * Server action for creating new chat conversations.
 *
 * @module features/chat/actions/create-chat.action
 */

"use server"

import { requireAuthAction } from "@/lib/auth/guards"
import type { RepositoryContext } from "@/lib/data/repositories"
import { chatService } from "@/lib/data/services/chat.service"
import type { Chat } from "@/lib/db/schema"
import { RateLimitError } from "@/lib/errors"
import { checkApiLimit, getRetryAfter } from "@/lib/rate-limit"

// =============================================================================
// Types
// =============================================================================

/**
 * Input for create chat action
 */
export interface CreateChatInput {
	/** Optional chat title */
	title?: string
	/** Optional visibility setting */
	visibility?: "public" | "private"
}

/**
 * Result of create chat action
 */
export interface CreateChatResult {
	/** Success status */
	success: boolean
	/** Created chat */
	chat?: Chat
	/** Error message if failed */
	error?: string
}

// =============================================================================
// Create Chat Action
// =============================================================================

/**
 * Create a new chat conversation.
 *
 * This action:
 * 1. Authenticates the user
 * 2. Checks rate limits
 * 3. Creates a new chat in the database
 *
 * @param input - Create chat input parameters
 * @returns Create chat result with the created chat
 * @throws UnauthorizedError if not authenticated
 * @throws RateLimitError if rate limit exceeded
 *
 * @example
 * ```typescript
 * const result = await createChatAction({
 *   title: 'My New Chat',
 *   visibility: 'private',
 * });
 * if (result.success) {
 *   console.log('Created chat:', result.chat.id);
 * }
 * ```
 */
export async function createChatAction(
	input: CreateChatInput = {},
): Promise<CreateChatResult> {
	// 1. Authenticate user
	const userId = await requireAuthAction()

	// 2. Check rate limit (use API limiter for chat creation)
	const rateLimitResult = await checkApiLimit(userId)
	if (!rateLimitResult.success) {
		const retryAfter = getRetryAfter(rateLimitResult.reset)
		throw new RateLimitError(
			"Too many requests. Please wait before creating another chat.",
			{ retryAfter },
		)
	}

	// 3. Create repository context
	const ctx: RepositoryContext = {
		userId,
		isGuest: false,
	}

	try {
		// 4. Create the chat
		const chat = await chatService.createChat(userId, input.title, ctx)

		return {
			success: true,
			chat,
		}
	} catch (error) {
		return {
			success: false,
			error:
				error instanceof Error
					? error.message
					: "Failed to create chat",
		}
	}
}

/**
 * Create a new chat with an initial ID.
 * Useful when the chat ID needs to be known before creation.
 *
 * @param chatId - Pre-determined chat ID
 * @param input - Create chat input parameters
 * @returns Create chat result
 */
export async function createChatWithId(
	_chatId: string,
	input: CreateChatInput = {},
): Promise<CreateChatResult> {
	// For now, delegate to createChatAction
	// The chat ID is generated by the service
	return createChatAction(input)
}
